use db_coffee;

DROP TABLE IF EXISTS shopping_products;
DROP TABLE IF EXISTS shopping_cart;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS products;

CREATE TABLE IF NOT EXISTS products (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    description VARCHAR(100) NOT NULL,
    longDescription TEXT,
    size VARCHAR(10) NOT NULL,
    price FLOAT NOT NULL,
    category VARCHAR(20) NOT NULL,
    img VARCHAR(100) DEFAULT 'img-default.jpg',
    sellingCategory VARCHAR(20)  NOT NULL,
    discount FLOAT, 
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    fullName VARCHAR(100) NOT NULL,
    birthDate DATE NOT NULL,
    email VARCHAR(70) NOT NULL,
    password VARCHAR(200) NOT NULL,
    type VARCHAR(20) NOT NULL DEFAULT 'user',
    avatar VARCHAR(100) DEFAULT 'img-default.jpg',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS shopping_cart (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
	updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS shopping_products (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
    shopping_cart_id INTEGER NOT NULL,
    product_id INTEGER NOT NULL,
    units INTEGER NOT NULL,
    FOREIGN KEY (shopping_cart_id) REFERENCES shopping_cart(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);